# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish

on:
  release:
    types: [published]
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Semver Parse
      id: semver
      uses: release-kit/semver@v1
      with:
        fallback: 'v3.4.5-pre'
        
    - name: prepare version patch
      run: |
        echo '<Project>' > ./src/Version.props
        echo '	<PropertyGroup>' >> ./src/Version.props
        echo '    <AssemblyVersion>@@@Major@@@.@@@Minor@@@.@@@Patch@@@</AssemblyVersion>' >> ./src/Version.props
        echo '    <FileVersion>@@@Major@@@.@@@Minor@@@.@@@Patch@@@-@@@SHA@@@</FileVersion>' >> ./src/Version.props
        echo '    <PackageVersion>@@@Major@@@.@@@Minor@@@.@@@Patch@@@@@@PreRelease@@@</PackageVersion>' >> ./src/Version.props
        echo '    <InformationalVersion>@@@Major@@@.@@@Minor@@@.@@@Patch@@@@@@PreRelease@@@-@@@SHA@@@</InformationalVersion>' >> ./src/Version.props
        echo '	</PropertyGroup>' >> ./src/Version.props
        echo '</Project>' >> ./src/Version.props
        cat ./src/Version.props
          
    - name: Replace major-version
      uses: alexrogalskiy/github-action-tag-replacer@master
      with:
        prefix: '@@@'
        suffix: '@@@'
        sourceFile: './src/Version.props'
        placeholder: 'Major'
        replacement: ${{ steps.semver.outputs.major }}
        
    - name: Replace minor-version
      uses: alexrogalskiy/github-action-tag-replacer@master
      with:
        prefix: '@@@'
        suffix: '@@@'
        sourceFile: './src/Version.props'
        placeholder: 'Minor'
        replacement: ${{ steps.semver.outputs.minor }}
        
    - name: Replace patch-version
      uses: alexrogalskiy/github-action-tag-replacer@master
      with:
        prefix: '@@@'
        suffix: '@@@'
        sourceFile: './src/Version.props'
        placeholder: 'Patch'
        replacement: ${{ steps.semver.outputs.patch }}
        
    - name: Replace patch-version
      uses: alexrogalskiy/github-action-tag-replacer@master
      with:
        prefix: '@@@'
        suffix: '@@@'
        sourceFile: './src/Version.props'
        placeholder: 'Patch'
        replacement: ${{ steps.semver.outputs.patch }}
        
    - name: Replace prerelease-version
      uses: alexrogalskiy/github-action-tag-replacer@master
      with:
        prefix: '@@@'
        suffix: '@@@'
        sourceFile: './src/Version.props'
        placeholder: 'PreRelease'
        replacement: ${{ steps.semver.outputs.prerelease  }}
        
    - name: Replace prerelease-version
      uses: alexrogalskiy/github-action-tag-replacer@master
      with:
        prefix: '@@@'
        suffix: '@@@'
        sourceFile: './src/Version.props'
        placeholder: 'SHA'
        replacement: ${{github.sha}}
    
    - name: show version patch
      uses: actions/github-script@v6
      with:
        script: |
          cat ./src/Version.props
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore        
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release --no-build --verbosity normal
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: "**/*.nupkg"
