# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish

on:
  release:
    types: [published]
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Semver Parse
      id: semver
      uses: release-kit/semver@v1
      with:
        fallback: 'v0.3.0-pre'
        
    - name: prepare version patch
      run: |
        echo '<Project>' > ./src/Version.props
        echo '  <PropertyGroup>' >> ./src/Version.props
        echo '    <AssemblyVersion>@@@AssemblyVersion@@@</AssemblyVersion>' >> ./src/Version.props
        echo '    <FileVersion>@@@FileVersion@@@</FileVersion>' >> ./src/Version.props
        echo '    <PackageVersion>@@@PackageVersion@@@</PackageVersion>' >> ./src/Version.props
        echo '    <InformationalVersion>@@@InformationalVersion@@@</InformationalVersion>' >> ./src/Version.props
        echo '  </PropertyGroup>' >> ./src/Version.props
        echo '</Project>' >> ./src/Version.props
        cat ./src/Version.props
          
    - name: Replace AssemblyVersion
      uses: alexrogalskiy/github-action-tag-replacer@master
      with:
        sourceFile: './src/Version.props'
        placeholder: '@@@AssemblyVersion@@@'
        replacement: '${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}.${{ steps.semver.outputs.patch }}'
        
    - name: Replace FileVersion
      uses: alexrogalskiy/github-action-tag-replacer@master
      with:
        sourceFile: './src/Version.props'
        placeholder: '@@@FileVersion@@@'
        replacement: '${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}.${{ steps.semver.outputs.patch }}'
        
    - name: Replace PackageVersion
      uses: alexrogalskiy/github-action-tag-replacer@master
      with:
        sourceFile: './src/Version.props'
        placeholder: '@@@PackageVersion@@@'
        replacement: '${{ steps.semver.outputs.full }}${{ github.run_number }}${{ github.run_attempt }}'
        
    - name: Replace InformationalVersion
      uses: alexrogalskiy/github-action-tag-replacer@master
      with:
        sourceFile: './src/Version.props'
        placeholder: '@@@InformationalVersion@@@'
        replacement: '${{ steps.semver.outputs.tag }}-${{ github.sha }}'
    
    - name: show version patch
      run: cat ./src/Version.props
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore        
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release --no-build --verbosity normal
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: "**/*.nupkg"
        
    - name: Publish
      run: dotnet nuget push "**/*.nupkg" -k "${{secrets.NUGET_APIKEY_TYPEALIZR}}" --skip-duplicate -s "https://api.nuget.org/v3/index.json"
